spring.application.name=student-webapp
spring.datasource.url=jdbc:postgresql://localhost:5432/student_webapp
spring.datasource.username=snehal
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect